import * as express from 'express';
import fetch from 'node-fetch';
import * as redis from 'redis';

const port = process.env.PORT || 5000;
const redisPort = Number(process.env.REDIS_PORT) || 6379;

const client = redis.createClient({
  port: redisPort,
});

const app = express();

// Generated by https://quicktype.io

interface User {
  login: string;
  id: number;
  node_id: string;
  avatar_url: string;
  gravatar_id: string;
  url: string;
  html_url: string;
  followers_url: string;
  following_url: string;
  gists_url: string;
  starred_url: string;
  subscriptions_url: string;
  organizations_url: string;
  repos_url: string;
  events_url: string;
  received_events_url: string;
  type: string;
  site_admin: boolean;
  name: string;
  company: null;
  blog: string;
  location: null;
  email: null;
  hireable: null;
  bio: null;
  public_repos: number;
  public_gists: number;
  followers: number;
  following: number;
  created_at: string;
  updated_at: string;
}

const fetchReposCount: express.Handler = function(req, res, next) {
  const {
    params: { username },
  } = req;

  console.log('fetching repos count for', username);
  fetch(`https://api.github.com/users/${username}`)
    .then(res => res.json())
    .then(({ public_repos }: User) => public_repos)
    .then(
      publicRepos =>
        `<div>Public repos for <i>${username}</i>: <strong>${publicRepos}</strong></div>`,
    )
    .then(repos => res.send(repos))
    .catch(console.error);
};

app.get('/repos/:username', fetchReposCount);

app.listen(port, () => {
  console.log(`http://localhost:${port}`);
});
